# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sarah Hersh | Web Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sarah Hersh - Web Developer, Writer, Educator
baseurl: "" # the subpath of your site, e.g. /blog
url: "sarahchersh.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["*.scss", "main.js", "node_modules", "webpack.config.js", "Gemfile", "Gemfile.lock", "package.json"]
# keep_files: ["assets/javascripts/critical.bundle.js", "assets/javascripts/bundle.js", "assets/stylesheets/main.css"]
